# Dataset 2 : GSE42830_series_matrix

In [1]:
# Import necessary library
import pandas as pd

# Set the file path for the input TXT file
file_path = r"..\..\..\Datasets\train\raw\GSE42830_series_matrix.txt"

# Load the TXT file into a Pandas DataFrame, skipping metadata lines
dataset2 = pd.read_csv(file_path, sep='\t', skiprows=50)

C:\Users\dilan\AppData\Local\Temp\ipykernel_40500\3591842383.py:8: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset2 = pd.read_csv(file_path, sep='\t', skiprows=50)

In [2]:
# Display the first 5 rows
dataset2.head()

,!Sample_title,Control Sample 1 training set,Cancer Sample 2 training set,Sarcoid Sample 3 training set,Sarcoid Sample 4 training set,Control Sample 5 training set,Sarcoid Sample 6 training set,TB Sample 7 training set,Control Sample 8 training set,Cancer Sample 9 training set,...,Control Sample 86 training set,TB Sample 87 training set,Control Sample 88 training set,Control Sample 89 training set,Control Sample 90 training set,Cancer Sample 91 training set,Pneumonia Sample 92 training set,Control Sample 93 training set,Sarcoid Sample 94 training set,Sarcoid Sample 95 training set
0,!Sample_geo_accession,GSM1050928,GSM1050929,GSM1050930,GSM1050931,GSM1050932,GSM1050933,GSM1050934,GSM1050935,GSM1050936,...,GSM1051013,GSM1051014,GSM1051015,GSM1051016,GSM1051017,GSM1051018,GSM1051019,GSM1051020,GSM1051021,GSM1051022
1,!Sample_status,Public on Oct 31 2013,Public on Oct 31 2013,Public on Oct 31 2013,Public on Oct 31 2013,Public on Oct 31 2013,Public on Oct 31 2013,Public on Oct 31 2013,Public on Oct 31 2013,Public on Oct 31 2013,...,Public on Oct 31 2013,Public on Oct 31 2013,Public on Oct 31 2013,Public on Oct 31 2013,Public on Oct 31 2013,Public on Oct 31 2013,Public on Oct 31 2013,Public on Oct 31 2013,Public on Oct 31 2013,Public on Oct 31 2013
2,!Sample_submission_date,Dec 10 2012,Dec 10 2012,Dec 10 2012,Dec 10 2012,Dec 10 2012,Dec 10 2012,Dec 10 2012,Dec 10 2012,Dec 10 2012,...,Dec 10 2012,Dec 10 2012,Dec 10 2012,Dec 10 2012,Dec 10 2012,Dec 10 2012,Dec 10 2012,Dec 10 2012,Dec 10 2012,Dec 10 2012
3,!Sample_last_update_date,Oct 31 2013,Oct 31 2013,Oct 31 2013,Oct 31 2013,Oct 31 2013,Oct 31 2013,Oct 31 2013,Oct 31 2013,Oct 31 2013,...,Oct 31 2013,Oct 31 2013,Oct 31 2013,Oct 31 2013,Oct 31 2013,Oct 31 2013,Oct 31 2013,Oct 31 2013,Oct 31 2013,Oct 31 2013
4,!Sample_type,RNA,RNA,RNA,RNA,RNA,RNA,RNA,RNA,RNA,...,RNA,RNA,RNA,RNA,RNA,RNA,RNA,RNA,RNA,RNA

## Get the transpose of the dataset

In [3]:
# Transpose the dataset
transpose_dataset2 = dataset2.T

# Reset the index to make the transposed column names into a header
transpose_dataset2.columns = transpose_dataset2.iloc[0]
transpose_dataset2 = transpose_dataset2.drop(transpose_dataset2.index[0])

# Display the first few rows of the transposed data
transpose_dataset2.head()

!Sample_title,!Sample_geo_accession,!Sample_status,!Sample_submission_date,!Sample_last_update_date,!Sample_type,!Sample_channel_count,!Sample_source_name_ch1,!Sample_organism_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,...,ILMN_3311150,ILMN_3311155,ILMN_3311160,ILMN_3311165,ILMN_3311170,ILMN_3311175,ILMN_3311180,ILMN_3311185,ILMN_3311190,!series_matrix_table_end
Control Sample 1 training set,GSM1050928,Public on Oct 31 2013,Dec 10 2012,Oct 31 2013,RNA,1,Whole Blood,Homo sapiens,gender: F,ethnicity: Caucasian,...,-0.581782,-0.020077,-0.38827,-0.231975,-0.361991,-0.377701,-0.600778,-0.361991,0.558973,NaN
Cancer Sample 2 training set,GSM1050929,Public on Oct 31 2013,Dec 10 2012,Oct 31 2013,RNA,1,Whole Blood,Homo sapiens,gender: F,ethnicity: Caucasian,...,0.438028,0.187933,0.241973,-0.133255,0.268252,0.663968,0.029465,0.268252,-0.888026,NaN
Sarcoid Sample 3 training set,GSM1050930,Public on Oct 31 2013,Dec 10 2012,Oct 31 2013,RNA,1,Whole Blood,Homo sapiens,gender: M,ethnicity: Afro-Carribbean,...,-0.382173,-0.041067,-0.188661,-0.050628,-0.162382,-0.178092,-0.401169,-0.162382,0.318254,NaN
Sarcoid Sample 4 training set,GSM1050931,Public on Oct 31 2013,Dec 10 2012,Oct 31 2013,RNA,1,Whole Blood,Homo sapiens,gender: F,ethnicity: Caucasian,...,-0.295873,1.076259,-0.102362,1.171504,-0.076083,-0.091793,-0.31487,-0.076083,0.541636,NaN
Control Sample 5 training set,GSM1050932,Public on Oct 31 2013,Dec 10 2012,Oct 31 2013,RNA,1,Whole Blood,Homo sapiens,gender: M,ethnicity: Caucasian,...,-0.280974,-0.141502,-0.087462,0.965404,-0.061183,-0.076893,-0.29997,-0.061183,-0.486278,NaN

In [4]:
# Check basic information about the dataset, including data types and non-null counts
transpose_dataset2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 95 entries, Control Sample 1 training set to Sarcoid Sample 95 training set
Columns: 47357 entries, !Sample_geo_accession to !series_matrix_table_end
dtypes: object(47357)
memory usage: 34.3+ MB

## Handling Duplicate Rows

In [5]:
transpose_dataset2.drop_duplicates(subset=['ID_REF'], keep='first', inplace=True)

### Handling Duplicate Columns

In [6]:
# Identify columns that start with '!Sample_characteristics_ch1' by their index positions
# The duplicate columns are in positions known by inspection with indices 8, 9, 10, and 11
characteristics_indices = [8, 9, 10, 11]

# Extract and rename each column using its index position
transpose_dataset2['!Sample_gender'] = transpose_dataset2.iloc[:, characteristics_indices[0]]
transpose_dataset2['!Sample_ethnicity'] = transpose_dataset2.iloc[:, characteristics_indices[1]]
transpose_dataset2['!Sample_disease_state'] = transpose_dataset2.iloc[:, characteristics_indices[2]]
transpose_dataset2['!Sample_tissue'] = transpose_dataset2.iloc[:, characteristics_indices[3]]

# Drop the original duplicated columns by their indices
transpose_dataset2.drop(transpose_dataset2.columns[characteristics_indices], axis=1, inplace=True)

# Reorder the columns to place the new columns at the front
# Create a new order by specifying the newly created columns first
new_column_order = ['!Sample_gender', '!Sample_ethnicity', '!Sample_disease_state', '!Sample_tissue'] + \
                   [col for col in transpose_dataset2.columns if col not in ['!Sample_gender', '!Sample_ethnicity', '!Sample_disease_state', '!Sample_tissue']]

# Reassign columns to the DataFrame in the new order
transpose_dataset2 = transpose_dataset2[new_column_order]

In [7]:
# Display the first few rows of the transposed data
transpose_dataset2.head()

!Sample_title,!Sample_gender,!Sample_ethnicity,!Sample_disease_state,!Sample_tissue,!Sample_geo_accession,!Sample_status,!Sample_submission_date,!Sample_last_update_date,!Sample_type,!Sample_channel_count,...,ILMN_3311150,ILMN_3311155,ILMN_3311160,ILMN_3311165,ILMN_3311170,ILMN_3311175,ILMN_3311180,ILMN_3311185,ILMN_3311190,!series_matrix_table_end
Control Sample 1 training set,gender: F,ethnicity: Caucasian,disease state: Control,tissue: whole blood,GSM1050928,Public on Oct 31 2013,Dec 10 2012,Oct 31 2013,RNA,1,...,-0.581782,-0.020077,-0.38827,-0.231975,-0.361991,-0.377701,-0.600778,-0.361991,0.558973,NaN
Cancer Sample 2 training set,gender: F,ethnicity: Caucasian,disease state: lung cancer,tissue: whole blood,GSM1050929,Public on Oct 31 2013,Dec 10 2012,Oct 31 2013,RNA,1,...,0.438028,0.187933,0.241973,-0.133255,0.268252,0.663968,0.029465,0.268252,-0.888026,NaN
Sarcoid Sample 3 training set,gender: M,ethnicity: Afro-Carribbean,disease state: Active Sarcoid,tissue: whole blood,GSM1050930,Public on Oct 31 2013,Dec 10 2012,Oct 31 2013,RNA,1,...,-0.382173,-0.041067,-0.188661,-0.050628,-0.162382,-0.178092,-0.401169,-0.162382,0.318254,NaN
Sarcoid Sample 4 training set,gender: F,ethnicity: Caucasian,disease state: Non-active sarcoidosis,tissue: whole blood,GSM1050931,Public on Oct 31 2013,Dec 10 2012,Oct 31 2013,RNA,1,...,-0.295873,1.076259,-0.102362,1.171504,-0.076083,-0.091793,-0.31487,-0.076083,0.541636,NaN
Control Sample 5 training set,gender: M,ethnicity: Caucasian,disease state: Control,tissue: whole blood,GSM1050932,Public on Oct 31 2013,Dec 10 2012,Oct 31 2013,RNA,1,...,-0.280974,-0.141502,-0.087462,0.965404,-0.061183,-0.076893,-0.29997,-0.061183,-0.486278,NaN

## Unnecessary Feature Elemination

In [8]:
# Identify columns where all values are the same
columns_to_drop = transpose_dataset2.columns[transpose_dataset2.nunique() == 1]

# Drop those columns
data2 = transpose_dataset2.drop(columns=columns_to_drop)

In [9]:
# Drop columns with more than 50% missing values
# Calculate threshold for dropping columns
threshold = len(data2) * 0.5
data2 = data2.dropna(thresh=threshold, axis=1)

In [10]:
# Drop the columns which wonâ€™t contribute to distinguishing TB states.
columns_to_drop = [
    '!Sample_geo_accession','!Sample_gender','!Sample_ethnicity','ID_REF'
]

data2.drop(columns=columns_to_drop, inplace=True)

In [11]:
# Select the first 5 columns
first_5_columns = data2.columns[:5]

# Create an empty list to store the rows
rows = []

# Loop through each of the first 5 columns
for col in first_5_columns:
    # Get the data type of the column using the Series dtype
    data_type = data2[col].dtypes  # Access the dtype via .dtypes (not .dtype)

    # Get the first two row values of the column
    row_value_1 = data2[col].iloc[0]
    row_value_2 = data2[col].iloc[1]

    # Append the information as a row to the list
    rows.append({
        'Feature': col,
        'Data Type': data_type,
        'Row Value 1': row_value_1,
        'Row Value 2': row_value_2
    })

# Convert the list of rows into a DataFrame
result_df = pd.DataFrame(rows)

# Display the result
result_df

,Feature,Data Type,Row Value 1,Row Value 2
0,!Sample_disease_state,object,disease state: Control,disease state: lung cancer
1,ILMN_1343291,object,0.21518898,-0.3297348
2,ILMN_1343295,object,-0.38641214,-0.24578714
3,ILMN_1651199,object,-0.38827038,0.24197292
4,ILMN_1651209,object,-0.5748668,0.05537653

## Handling Missing values

In [12]:
# Check for missing values
data2.isnull().sum()

!Sample_title
!Sample_disease_state    0
ILMN_1343291             0
ILMN_1343295             0
ILMN_1651199             0
ILMN_1651209             0
                        ..
ILMN_3311170             0
ILMN_3311175             0
ILMN_3311180             0
ILMN_3311185             0
ILMN_3311190             0
Length: 47324, dtype: int64

In [13]:
# Check for missing values and print only columns with missing values
missing_values = data2.isnull().sum()
print(missing_values[missing_values > 0])

Series([], dtype: int64)

## Creating the Target Column - TB_Status

In [14]:
# Get unique categories in the "!Sample_disease_state" column
unique_categories = data2["!Sample_disease_state"].unique()

# Display the unique categories
unique_categories

array(['disease state: Control', 'disease state: lung cancer',
       'disease state: Active Sarcoid',
       'disease state: Non-active sarcoidosis', 'disease state: TB',
       'disease state: Baseline'], dtype=object)

In [15]:
# Define a function to categorize each sample type
def categorize_sample_type(source_name):
    source_name = source_name.lower()
    if 'tb' in source_name:
        return 'TB'
    elif 'control' in source_name:
        return 'Healthy Control'
    else:
        return 'Other Disease'  # Other lung disease like 'Lung Cancer'

# Apply the function to the "!Sample_disease_state" column
data2['TB_Status'] = data2['!Sample_disease_state'].apply(categorize_sample_type)

# Display unique values in the new 'TB_Status' column to verify
print(data2['TB_Status'].unique())

['Healthy Control' 'Other Disease' 'TB']

In [16]:
data2.sample(5)

!Sample_title,!Sample_disease_state,ILMN_1343291,ILMN_1343295,ILMN_1651199,ILMN_1651209,ILMN_1651210,ILMN_1651221,ILMN_1651228,ILMN_1651229,ILMN_1651230,...,ILMN_3311150,ILMN_3311155,ILMN_3311160,ILMN_3311165,ILMN_3311170,ILMN_3311175,ILMN_3311180,ILMN_3311185,ILMN_3311190,TB_Status
Sarcoid Sample 4 training set,disease state: Non-active sarcoidosis,-0.07109833,0.051579952,-0.10236168,0.9313717,-0.33807564,-0.55319977,-0.12342358,0.19440031,-0.20113993,...,-0.295873,1.076259,-0.102362,1.171504,-0.076083,-0.091793,-0.31487,-0.076083,0.541636,Other Disease
TB Sample 67 training set,disease state: TB,-0.001932144,0.35865355,0.29304695,0.10645056,0.057332993,0.3782618,-0.16250706,0.32816124,0.1942687,...,0.099535,0.239007,0.293047,1.067197,0.319326,0.303616,0.080539,0.319326,0.84112,TB
Control Sample 30 training set,disease state: Control,0.6067476,-0.51394844,0.42212725,0.23553085,0.4732945,1.1476121,-0.0832715,-0.021548271,0.323349,...,0.228616,0.368087,0.422127,1.555559,0.448406,0.432696,0.209619,0.448406,0.376193,Healthy Control
Sarcoid Sample 59 training set,disease state: Active Sarcoid,-0.30475235,-0.33427763,0,-0.1865964,-0.23571396,0.41310024,-0.28824043,-0.4670396,-0.09877825,...,-0.193511,-0.05404,0.0,0.529913,0.026279,0.010569,1.586579,0.348207,0.48824,Other Disease
Pneumonia Sample 36 training set,disease state: Baseline,-0.033517838,0.68552065,-0.052088737,0.20492148,-0.2878027,-0.5029268,-0.6429491,-0.47848606,-0.15086699,...,-0.2456,0.633719,-0.052089,1.187929,-0.02581,-0.04152,-0.062963,-0.02581,0.922249,Other Disease

In [17]:
# Drop the '!Sample_disease_state' column.
data2.drop('!Sample_disease_state', axis=1, inplace=True)

## Data Type Conversion

In [18]:
# Convert columns that should be numeric (e.g., ILMN_1343291, ILMN_1343295)
# Select columns that start with "ILMN_"
ilmn_columns = data2.columns[data2.columns.str.startswith('ILMN_')]

# Convert all 'ILMN_' columns to numeric
data2[ilmn_columns] = data2[ilmn_columns].apply(pd.to_numeric, errors='coerce')

# Verify the data types of the columns
print(data2[ilmn_columns].dtypes)

!Sample_title
ILMN_1343291    float64
ILMN_1343295    float64
ILMN_1651199    float64
ILMN_1651209    float64
ILMN_1651210    float64
                 ...
ILMN_3311170    float64
ILMN_3311175    float64
ILMN_3311180    float64
ILMN_3311185    float64
ILMN_3311190    float64
Length: 47323, dtype: object

In [19]:
# Convert target column ('TB_Status') to categorical
data2['TB_Status'] = data2['TB_Status'].astype('category')

# Verify the data type of the column
print(data2['TB_Status'].dtypes)

category

In [20]:
dataset2 = data2.copy()

## Encode the target labels in the target column (TB_Status)

In [21]:
data2 = dataset2.copy()

## Standardizing/Normalizing Numeric Data

In [22]:
from sklearn.preprocessing import StandardScaler

# Select only the numeric columns in the dataset
numeric_columns = data2.select_dtypes(include=['float64', 'int64']).columns

# Initialize the scaler
scaler = StandardScaler()

# Fit the scaler on the numeric columns and transform them
data2[numeric_columns] = scaler.fit_transform(data2[numeric_columns])

# Display random 5 rows to verify the standardization
data2.sample(5)

!Sample_title,ILMN_1343291,ILMN_1343295,ILMN_1651199,ILMN_1651209,ILMN_1651210,ILMN_1651221,ILMN_1651228,ILMN_1651229,ILMN_1651230,ILMN_1651232,...,ILMN_3311150,ILMN_3311155,ILMN_3311160,ILMN_3311165,ILMN_3311170,ILMN_3311175,ILMN_3311180,ILMN_3311185,ILMN_3311190,TB_Status
Control Sample 70 training set,0.494881,0.504181,-0.099961,-0.458578,-0.443033,0.013566,0.911786,-0.596829,-0.283656,-0.415776,...,0.756159,-0.242850,-0.077651,0.115126,1.706065,-0.117033,1.423913,-0.030077,0.552503,Healthy Control
TB Sample 67 training set,-0.055040,0.615561,0.606127,0.026543,0.059022,0.410550,-0.342302,0.850507,0.304288,0.072719,...,0.088779,0.410610,0.663051,1.603579,0.675514,0.556601,0.028010,0.710729,1.193306,TB
TB Sample 52 training set,-1.407351,0.009289,0.940399,0.256207,0.296702,-0.303777,-0.523464,-1.026469,0.582628,0.303980,...,0.338795,0.719966,1.013709,1.791540,1.014716,0.875509,0.248637,1.061437,0.497406,TB
Control Sample 62 training set,0.659117,-0.535733,1.028025,0.316411,0.359007,-0.256579,0.664998,0.213185,0.655592,0.364602,...,0.404334,0.801061,1.105630,-0.296705,1.103634,0.959107,0.306471,1.153371,-1.045329,Healthy Control
Cancer Sample 9 training set,1.171982,0.136107,-1.688712,-1.550139,-1.572694,1.253946,0.952567,-0.520013,-1.606572,-0.775968,...,-1.627631,-1.713182,-1.744284,-1.156977,-1.653173,-1.632761,-1.486629,-1.696947,0.329162,Other Disease

## Handling Outliers

In [23]:
import numpy as np

# Select only the numeric columns
numeric_columns = data2.select_dtypes(include=['float64', 'int64']).columns

# Define a function to cap outliers
def cap_outliers(series):
    # Calculate Q1 (25th percentile) and Q3 (75th percentile)
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1

    # Define the lower and upper bounds
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Cap values outside the bounds to the respective bounds
    return np.where(series < lower_bound, lower_bound,
                    np.where(series > upper_bound, upper_bound, series))

# Apply the function to each numeric column
for col in numeric_columns:
    data2[col] = cap_outliers(data2[col])

# Display the random 5 rows to verify the changes
data2.sample(5)

!Sample_title,ILMN_1343291,ILMN_1343295,ILMN_1651199,ILMN_1651209,ILMN_1651210,ILMN_1651221,ILMN_1651228,ILMN_1651229,ILMN_1651230,ILMN_1651232,...,ILMN_3311150,ILMN_3311155,ILMN_3311160,ILMN_3311165,ILMN_3311170,ILMN_3311175,ILMN_3311180,ILMN_3311185,ILMN_3311190,TB_Status
TB Sample 74 training set,-0.225780,0.745844,2.097694,1.051333,1.119581,0.319586,0.296837,0.619141,1.546281,1.104636,...,1.204386,1.791002,2.227736,0.273588,2.189080,1.979612,1.012474,2.275636,-0.543947,TB
Sarcoid Sample 17 training set,-1.740491,0.099538,1.094891,2.167042,0.406551,-0.220562,-1.657164,-2.195121,0.711270,0.410863,...,0.454346,0.862943,1.175774,-0.261055,1.171487,1.022900,0.350604,1.223525,0.995513,Other Disease
Cancer Sample 34 training set,-0.039237,1.357382,-0.431135,1.049578,-0.678510,0.234720,-0.941559,0.296267,-0.559417,-0.644894,...,-0.687035,-0.549340,-0.425060,0.175530,-0.377048,-0.432986,-0.656604,-0.377536,1.671049,Other Disease
Sarcoid Sample 19 training set,-1.046190,-0.999275,-0.739452,0.305749,0.304741,2.920951,-0.847697,-1.477031,-0.816145,-0.858198,...,2.250262,-0.834675,-0.748490,-1.239033,-0.689911,-0.727131,-0.860098,-0.701012,1.654735,Other Disease
Sarcoid Sample 46 training set,-0.525700,-0.029180,0.004373,-0.386895,-0.368848,-0.139678,-0.282286,0.697377,-0.196779,-0.343595,...,-0.361300,-0.146292,0.031798,0.504417,0.064884,-0.017495,1.429343,0.079387,-0.975582,Other Disease

In [24]:
# Save the DataFrame as a CSV file
output_csv_path = r"..\..\..\Datasets\train\processed\processed_dataset2.csv"
data2.to_csv(output_csv_path, index=False)
print("CSV file saved to:", output_csv_path)

CSV file saved to: ..\..\..\Datasets\train\processed\processed_dataset2.csv